name: Publish JellyCon

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        py_version: [ 'py2', 'py3' ]
    steps:
      - name: Update Draft
        uses: release-drafter/release-drafter@v6.1.0
        if: ${{ matrix.py_version == 'py3' }}
        with:
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.JF_BOT_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyyaml

      - name: Create ${{ matrix.py_version }} addon.xml
        run: python build.py --version ${{ matrix.py_version }}

      - name: Publish Build Artifact
        uses: actions/upload-artifact@v4
        with:
          retention-days: 14
          name: ${{ matrix.py_version }}-build-artifact
          path: |
            *.zip

      - name: Upload to repo server
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -vrptz
          path: '*.zip'
          remote_path: /srv/incoming/kodi
          remote_host: ${{ secrets.REPO_HOST }}
          remote_user: ${{ secrets.REPO_USER }}
          remote_key: ${{ secrets.REPO_KEY }}

      - name: Add to Kodi repo and clean up
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.REPO_HOST  }}
          username: ${{ secrets.REPO_USER }}
          key: ${{ secrets.REPO_KEY }}
          script_stop: true
          script: |
            python3 /usr/local/bin/kodirepo add /srv/incoming/kodi/plugin.video.jellycon+${{ matrix.py_version }}.zip --datadir /srv/repository/main/client/kodi/${{ matrix.py_version }};
            rm /srv/incoming/kodi/plugin.video.jellycon+${{ matrix.py_version }}.zip;
